name: Crystal CI

on:
  push:
    branches: [ fu ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: aws2

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install user experience
      run: shards install
    - name: Run tests
      run: crystal spec
