name: Crystal CI

on:
  push:
    branches: [ space ]
  pull_request:
    branches: [ trying ]

jobs:
  build:

    runs-on: aws2

    container: help me learn this ///$hit
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install user experience
      run: shards install
    - name: Run tests
      run: crystal spec
